/* structs.c — generated by SUPER compiler. */
/* SPDX-License-Identifier: MIT */

#include <stdio.h>
#include <stdlib.h>

	typedef struct {
		} unknown;

int unknown() {
	}

	return 0;
int unknown() {
	}

	return 0;
