/*
 * c_codegen.c — C code generator for SUPER.
 */
/* SPDX-License-Identifier: MIT */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "c_codegen.h"

static void emit_c_stmt(FILE *f, ASTNode *node, int indent) {
    for (int i = 0; i < indent; i++) fprintf(f, "\t");

    switch (node->type) {
        case AST_FN_DEF:
        case AST_PUB_FN_DEF: {
            if (node->type == AST_PUB_FN_DEF) fprintf(f, "extern \"C\" ");
            fprintf(f, "int %s(", node->value ? node->value : "unknown");
            fprintf(f, ") {\n");
            if (node->children) {
                for (int i = 0; i < node->child_count; i++) {
                    emit_c_stmt(f, node->children[i], indent + 1);
                }
            }
            for (int i = 0; i < indent; i++) fprintf(f, "\t");
            fprintf(f, "}\n\n");
            break;
        }
        case AST_RETURN_STMT:
            fprintf(f, "\treturn 0;\n");
            break;
        case AST_VAR_DECL:
            fprintf(f, "\tint %s = 0;\n", node->value ? node->value : "unknown");
            break;
        case AST_STRUCT_DEF:
            fprintf(f, "\ttypedef struct {\n");
            if (node->children) {
                for (int i = 0; i < node->child_count; i++) {
                    emit_c_stmt(f, node->children[i], indent + 1);
                }
            }
            fprintf(f, "\t} %s;\n\n", node->value ? node->value : "unknown");
            break;
        default:
            break;
    }
}

int c_codegen_generate(ASTNode *ast, const char *output_file) {
    FILE *f = fopen(output_file, "w");
    if (!f) {
        fprintf(stderr, "Error: cannot open output file %s\n", output_file);
        return 0;
    }

    fprintf(f, "/* %s — generated by SUPER compiler. */\n", output_file);
    fprintf(f, "/* SPDX-License-Identifier: MIT */\n\n");
    fprintf(f, "#include <stdio.h>\n");
    fprintf(f, "#include <stdlib.h>\n\n");

    if (ast && ast->children) {
        for (int i = 0; i < ast->child_count; i++) {
            emit_c_stmt(f, ast->children[i], 0);
        }
    }

    fclose(f);
    return 1;
}

int c_codegen_generate_header(ASTNode *ast, const char *header_file) {
    FILE *f = fopen(header_file, "w");
    if (!f) {
        fprintf(stderr, "Error: cannot open header file %s\n", header_file);
        return 0;
    }

    fprintf(f, "/* %s — generated by SUPER compiler. */\n", header_file);
    fprintf(f, "/* SPDX-License-Identifier: MIT */\n\n");
    fprintf(f, "#ifndef SUPER_GENERATED_H\n");
    fprintf(f, "#define SUPER_GENERATED_H\n\n");

    if (ast && ast->children) {
        for (int i = 0; i < ast->child_count; i++) {
            ASTNode *child = ast->children[i];
            if (child->type == AST_FN_DEF || child->type == AST_PUB_FN_DEF) {
                fprintf(f, "int %s();\n", child->value ? child->value : "unknown");
            }
        }
    }

    fprintf(f, "\n#endif\n");
    fclose(f);
    return 1;
}
